prome_query_log:
  prome_log_path: /opt/logs/prometheus_query.log # prometheus query log文件path 和prometheus query配置保持一致
  heavy_query_threhold: 0.0001                   # heavy_query阈值，单位秒，依据情况修改
  py_name: parse_prome_query_log.py            # 主文件名。不动
  local_work_dir: all_prome_query_log # parser拉取query_log的保存路径，默认当前目录下的all_prome_query_log
  local_record_yml_dir: local_record_yml_dir # 写入本地的record yaml结果，默认当前目录下的 local_record_yml_dir
  check_heavy_query_api: http://localhost:9090  # 一个prometheus查询地址，用来double_check记录是否真的heavy，避免误添加。默认不启用这个功能

redis:
  host: localhost  # redis地址
  port: 6379
  redis_set_key: hke:heavy_query_set
  redis_one_key_prefix: hke:heavy_expr # heavy_query key前缀
consul:
  host: localhost  #consul地址
  port: 8500
  consul_record_key_prefix: prometheus/records #  heavy_query key前缀

heavy_blacklist_metrics:   # 黑名单metric_names
  - kafka_log_log_logendoffset
  - requests_latency_bucket
  - count(node_cpu_seconds_total)
  - '{__name__=~".+"}'
  - '{__name__=~".*"}'